# Generated by Django 4.0.4 on 2022-05-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_remove_uploadfile_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
