# Generated by Django 4.0.4 on 2022-05-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_uploadfile_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
    ]
