# Generated by Django 4.0.4 on 2022-05-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0007_alter_uploadfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='id',
            field=models.CharField(auto_created=True, max_length=250, primary_key=True, serialize=False),
        ),
    ]
