# Generated by Django 4.0.4 on 2022-05-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0009_alter_uploadfile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='summary',
        ),
    ]
